# Generated by Django 4.2.5 on 2024-07-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('감독', '감독'), ('배우', '배우'), ('성우', '성우'), ('연출', '연출'), ('음향', '음향'), ('조명', '조명'), ('의상', '의상'), ('메이크업', '메이크업'), ('아역', '아역'), ('모델', '모델'), ('인플루언서', '인플루언서')], max_length=20)),
                ('profile_photo', models.ImageField(blank=True, upload_to='profile_photo', verbose_name='프로필사진')),
                ('email', models.EmailField(blank=True, max_length=128, verbose_name='이메일')),
                ('one_line', models.CharField(blank=True, max_length=128, verbose_name='한줄소개')),
                ('intro', models.TextField(blank=True, verbose_name='소개글')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
