# Generated by Django 4.2.5 on 2024-07-01 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_portfolio_user_alter_portfolio_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='role',
        ),
        migrations.CreateModel(
            name='PortfolioRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios_portfoliorole', to='portfolios.portfolio')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_portfoliorole', to='portfolios.role')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='role',
            field=models.ManyToManyField(related_name='portfolios', through='portfolios.PortfolioRole', to='portfolios.role'),
        ),
    ]
