# Generated by Django 4.2.5 on 2024-07-01 16:23

from django.db import migrations, models
import portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_portfolio_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=portfolios.models.upload_filepath, verbose_name='프로필사진'),
        ),
    ]
