# Generated by Django 4.2.5 on 2024-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_alter_portfolio_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
