# Generated by Django 4.2.5 on 2024-07-01 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_portfolio_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_title', models.CharField(max_length=128, verbose_name='작품명')),
                ('career_role', models.CharField(max_length=128, verbose_name='역할')),
                ('career_year', models.DateField(verbose_name='연도')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='portfolios.portfolio')),
            ],
        ),
    ]
