# Generated by Django 4.2.5 on 2024-07-02 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolios', '0008_career_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('cast', models.CharField(blank=True, max_length=128, verbose_name='출연진')),
                ('staff', models.CharField(blank=True, max_length=128, verbose_name='스탭')),
                ('price', models.IntegerField(blank=True, default=1000, verbose_name='가격')),
                ('keyword', models.TextField(blank=True, verbose_name='키워드')),
                ('synopsis', models.TextField(blank=True, verbose_name='시놉시스')),
                ('video', models.FileField(blank=True, upload_to=portfolios.models.upload_filepath, verbose_name='동영상')),
                ('myurl', models.URLField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='portfolios.portfolio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=portfolios.models.upload_filepath, verbose_name='이미지')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolios.portfolio')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
