# Generated by Django 4.2.5 on 2024-07-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_video_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='career_year',
            field=models.IntegerField(default=2024, null=True, verbose_name='연도'),
        ),
    ]
