# Generated by Django 5.0.6 on 2024-07-03 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0013_rename_author_career_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_likes', to='portfolios.video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='like',
            field=models.ManyToManyField(related_name='liked_videos', through='portfolios.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
