# Generated by Django 4.2.5 on 2024-07-04 15:34

from django.db import migrations, models
import portfolios.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0017_like_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='profile_photo',
            field=models.ImageField(blank=True, default='media/default_mypage_image.jpg', upload_to=portfolios.models.upload_filepath, verbose_name='프로필사진'),
        ),
    ]
