# Generated by Django 5.0.6 on 2024-06-30 07:48

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mypage_image',
            field=models.ImageField(blank=True, default='media/default_mypage_image.jpg', upload_to=accounts.models.upload_filepath),
        ),
    ]
