# Generated by Django 5.0.6 on 2024-06-30 11:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_mypage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mypage_image',
            field=models.ImageField(blank=True, default='media/default_mypage_image.jpeg', upload_to=accounts.models.upload_filepath),
        ),
    ]
